- type: job
  id: BlueshieldOfficer
  name: офицер синего щита
  description: "Выступайте в роли телохранителя и советника для VIP-персон Командования и ЦентКома."
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 90000 # 25 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 # 25 hours
    - !type:AgeRequirement
      requiredAge: 21
  goobcoins: 45
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - BlueshieldOfficer
  - Service
  - Hydroponics
  - Cargo
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ] # Go big, or go home.
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    eyes: ClothingEyesGlassesBSO
    gloves: ClothingHandsGlovesCombat
    id: BlueshieldPDA
    ears: ClothingHeadsetAltBlueshield
    belt: ClothingBeltAssaultFilled
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
  storage:
    back:
    - Flash
    - SecHypo
    - ClothingMaskGasSecurity
